controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
  - name: gripper
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      []
  - name: follow
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      []
